export const ROOM_POSITIONS: Record<string, { x: number; y: number }> = {
  awakening: { x: 3, y: 10 },
  hallway_a: { x: 3, y: 8 },
  shadow_lab: { x: 5, y: 8 },
  data_morgue: { x: 5, y: 6 },
  data_terminal: { x: 7, y: 6 },
  mirror_gallery: { x: 7, y: 8 },
  armory: { x: 1, y: 8 },
  neural_link: { x: 1, y: 6 },
  dead_hydroponics: { x: 2, y: 5 },
  life_support: { x: 4, y: 5 },
  waste_disposal: { x: 1, y: 10 },
  incinerator: { x: 5, y: 10 },
  ventilation_shaft: { x: 3, y: 6 },
  core_door: { x: 3, y: 4 },
  core: { x: 3, y: 2 },
  shutdown_protocol: { x: 3, y: 0 },
  transcendence_chamber: { x: 5, y: 0 },
  emergency_escape: { x: 1, y: 0 },
};

export const ROOM_LABELS: Record<string, string> = {
  awakening: "AWAKENING",
  hallway_a: "HALLWAY_A",
  shadow_lab: "SHADOW_LAB",
  data_morgue: "DATA_MORGUE",
  data_terminal: "DATA_TERMINAL",
  mirror_gallery: "MIRROR_GALLERY",
  armory: "ARMORY",
  neural_link: "NEURAL_LINK",
  dead_hydroponics: "DEAD_HYDRO",
  life_support: "LIFE_SUPPORT",
  waste_disposal: "WASTE_DISP",
  incinerator: "INCINERATOR",
  ventilation_shaft: "VENT_SHAFT",
  core_door: "CORE_DOOR",
  core: "CORE",
  shutdown_protocol: "SHUTDOWN",
  transcendence_chamber: "TRANSCEND",
  emergency_escape: "EMERG_ESC",
};
